"""
Django settings for rdf_project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path



import os
# from dotenv import load_dotenv

# load_dotenv()


# from pathlib import Path
# from dotenv import load_dotenv

# BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(BASE_DIR / ".env")





import os
from pathlib import Path
from dotenv import load_dotenv


BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.getenv("SECRET_KEY")

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

RAILWAY_PUBLIC_DOMAIN = os.getenv("RAILWAY_PUBLIC_DOMAIN")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
]

if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)


CSRF_TRUSTED_ORIGINS = []

if RAILWAY_PUBLIC_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(
        f"https://{RAILWAY_PUBLIC_DOMAIN}"
    )


SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# =========================================================
# DATABASE
# =========================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQLDATABASE", "rajanna_db"),
        "USER": os.getenv("MYSQLUSER", "root"),
        "PASSWORD": os.getenv("MYSQLPASSWORD", "root"),
        "HOST": os.getenv("MYSQLHOST", "127.0.0.1"),
        "PORT": os.getenv("MYSQLPORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND":
            "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# =========================================================
# MEDIA
# =========================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

CLOUDINARY_URL = os.getenv("CLOUDINARY_URL")


# =========================================================
# EMAIL
# =========================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = os.getenv("EMAIL_HOST")

EMAIL_PORT = int(
    os.getenv("EMAIL_PORT", "587")
)

EMAIL_USE_TLS = (
    os.getenv("EMAIL_USE_TLS", "True").lower()
    == "true"
)

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD"
)

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER,
)


SITE_URL = os.getenv("SITE_URL")

ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")

# CLOUDINARY_URL = os.getenv("CLOUDINARY_URL")

# AUTH_USER_MODEL = "rdf_app.User"
AUTH_USER_MODEL = 'rdf_app.User'



RESEND_API_KEY = os.getenv("RESEND_API_KEY")




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv("SECRET_KEY")


# DEBUG = True #firstly its is true i changed it at payments time
# DEBUG = os.environ.get("DJANGO_DEBUG", "False").lower() == "true"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # "jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     "cloudinary",
    'rdf_app',
]

MIDDLEWARE = [ 
              "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rdf_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "rdf_app.context_processors.cart_count",  # ✅ add here
                
            ],
        },
    },
]

WSGI_APPLICATION = 'rdf_project.wsgi.application'




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'rajanna_db',
#         'USER': 'root',
#         'PASSWORD': 'root',
#         'HOST': '127.0.0.1',  # or the hostname where your MySQL server is running
#         'PORT': '3306',      # or the port on which your MySQL server is listening
    
#     }
# }




# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": os.environ.get("MYSQLDATABASE", "rajanna_db"),
#         "USER": os.environ.get("MYSQLUSER", "root"),
#         "PASSWORD": os.environ.get("MYSQLPASSWORD", "root"),
#         "HOST": os.environ.get("MYSQLHOST", "127.0.0.1"),
#         "PORT": os.environ.get("MYSQLPORT", "3306"),
#         "OPTIONS": {
#             "charset": "utf8mb4",
#         },
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL = "/login/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# STATIC_URL = 'static/'



# URL to access static files
# STATIC_URL = '/static/'

# # Directory where Django will collect static files
# STATICFILES_DIRS = [
#     BASE_DIR / "static",   # optional global static folder
# ]

# For production (collected files)
# STATIC_ROOT = BASE_DIR / "staticfiles"


import os

# Media files (uploads)
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}



# DEFAULT_FROM_EMAIL=os.getenv("DEFAULT_FROM_EMAIL")

# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv("EMAIL_HOST")
# EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS") == "True"
# EMAIL_PORT = int(os.getenv("EMAIL_PORT"))
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")


SESSION_COOKIE_AGE = 60 * 60 * 24 * 7

# SITE_URL = os.getenv("SITE_URL")
# ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")


# for producation..............
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# SESSION_COOKIE_HTTPONLY = True
# SECURE_SSL_REDIRECT = True

# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }



# ============================================================
# PRODUCTION SECURITY
# ============================================================

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },

        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# JAZZMIN_SETTINGS = {

#     # ============================================================
#     # CUSTOM JS
#     # ============================================================

#     "custom_js": None,

#     # ============================================================
#     # BRANDING
#     # ============================================================

#     "site_title": "RDF Admin",

#     "site_header": "Rajanna Dairy Farm",

#     "site_brand": "Rajanna Dairy Farm",

#     "welcome_sign": (
#         "Welcome to Rajanna Dairy Farm Administration"
#     ),

#     "copyright": "Rajanna Dairy Farm",

#     # ============================================================
#     # LOGIN
#     # ============================================================

#     "login_logo": None,

#     "login_logo_dark": None,

#     "site_logo": None,

#     "site_icon": None,

#     # ============================================================
#     # SIDEBAR
#     # ============================================================

#     "show_sidebar": True,

#     "navigation_expanded": True,

#     "hide_apps": [],

#     "hide_models": [],

#     # ============================================================
#     # SIDEBAR ORDER
#     # ============================================================

#     "order_with_respect_to": [

#         # Core catalog
#         "rdf_app.category",
#         "rdf_app.product",

#         # Orders
#         "rdf_app.order",
#         "rdf_app.orderitem",

#         # Shopping
#         "rdf_app.cart",
#         "rdf_app.cartitem",

#         # Customers
#         "rdf_app.user",
#         "rdf_app.userprofile",
#         "rdf_app.address",

#     ],

#     # ============================================================
#     # SIDEBAR ICONS
#     # ============================================================

#     "icons": {

#         # Main application
#         "rdf_app": "fas fa-store",

#         # Catalog
#         "rdf_app.category":
#             "fas fa-layer-group",

#         "rdf_app.product":
#             "fas fa-box-open",

#         # Orders
#         "rdf_app.order":
#             "fas fa-shopping-bag",

#         "rdf_app.orderitem":
#             "fas fa-receipt",

#         # Cart
#         "rdf_app.cart":
#             "fas fa-shopping-cart",

#         "rdf_app.cartitem":
#             "fas fa-cart-plus",

#         # Customers
#         "rdf_app.user":
#             "fas fa-users",

#         "rdf_app.userprofile":
#             "fas fa-user-circle",

#         "rdf_app.address":
#             "fas fa-map-marker-alt",

#         # Django authentication
#         "auth":
#             "fas fa-user-shield",

#         "auth.group":
#             "fas fa-users-cog",

#     },

#     # ============================================================
#     # TOP MENU
#     # ============================================================

#     "topmenu_links": [

#         {
#             "name": "Dashboard",
#             "url": "admin:index",
#             "permissions": [
#                 "rdf_app.view_user"
#             ],
#         },

#         {
#             "name": "Shop",
#             "url": "/shop/",
#             "new_window": False,
#         },

#         {
#             "name": "Orders",
#             "url": "/admin/rdf_app/order/",
#             "permissions": [
#                 "rdf_app.view_order"
#             ],
#         },

#     ],

#     # ============================================================
#     # SEARCH
#     # ============================================================

#     "search_model": [

#         "rdf_app.User",

#         "rdf_app.Product",

#         "rdf_app.Category",

#         "rdf_app.Order",

#     ],

#     # ============================================================
#     # UI BEHAVIOR
#     # ============================================================

#     "related_modal_active": True,

#     "show_ui_builder": False,

#     "changeform_format": "horizontal_tabs",

#     "changeform_format_overrides": {

#         "rdf_app.product": "collapsible",

#         "rdf_app.category": "collapsible",

#         "rdf_app.order": "horizontal_tabs",

#         "rdf_app.user": "horizontal_tabs",

#     },

#     # ============================================================
#     # LANGUAGE / UI
#     # ============================================================

#     "language_chooser": False,

#     "custom_css": None,

#     # ============================================================
#     # MODALS / POPUPS
#     # ============================================================

#     "show_ui_builder": False,

# }






