# Generated by Django 4.2.30 on 2026-09-08 14:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_app', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='category_image')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('seo_title', models.CharField(blank=True, default='', max_length=160)),
                ('seo_description', models.CharField(blank=True, default='', max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='categories_is_acti_48a428_idx'), models.Index(fields=['is_featured', 'is_active'], name='categories_is_feat_9b3b1e_idx')],
            },
        ),
    ]
