# Generated by Django 4.2.30 on 2026-09-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_app', '0007_alter_category_id_alter_emailverificationtoken_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
    ]
