# Generated by Django 4.2.30 on 2026-09-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_app', '0011_order_orderitem_order_order_user_created_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
