# Generated by Django 4.2.30 on 2026-09-10 10:49

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_app', '0012_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_subscriptions', to='rdf_app.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'milk_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilkSubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('frequency', models.CharField(choices=[('daily', 'Daily')], default='daily', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milk_subscription_items', to='rdf_app.product')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rdf_app.milksubscription')),
            ],
            options={
                'db_table': 'milk_subscription_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MilkDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(db_index=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('delivered', 'Delivered'), ('skipped', 'Skipped'), ('missed', 'Missed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='rdf_app.milksubscription')),
                ('subscription_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='rdf_app.milksubscriptionitem')),
            ],
            options={
                'db_table': 'milk_deliveries',
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilkBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.PositiveSmallIntegerField()),
                ('billing_year', models.PositiveSmallIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pending_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], db_index=True, default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='rdf_app.milksubscription')),
            ],
            options={
                'db_table': 'milk_bills',
                'ordering': ['-billing_year', '-billing_month'],
            },
        ),
        migrations.AddIndex(
            model_name='milksubscriptionitem',
            index=models.Index(fields=['subscription'], name='milk_sub_item_sub_idx'),
        ),
        migrations.AddIndex(
            model_name='milksubscriptionitem',
            index=models.Index(fields=['product'], name='milk_sub_item_product_idx'),
        ),
        migrations.AddIndex(
            model_name='milksubscription',
            index=models.Index(fields=['user', 'status'], name='milk_sub_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='milksubscription',
            index=models.Index(fields=['status', 'start_date'], name='milk_sub_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='milkdelivery',
            index=models.Index(fields=['subscription', 'delivery_date'], name='milk_delivery_sub_date_idx'),
        ),
        migrations.AddIndex(
            model_name='milkdelivery',
            index=models.Index(fields=['delivery_date', 'status'], name='milk_delivery_date_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='milkdelivery',
            constraint=models.UniqueConstraint(fields=('subscription_item', 'delivery_date'), name='unique_milk_delivery_day'),
        ),
        migrations.AddIndex(
            model_name='milkbill',
            index=models.Index(fields=['subscription', 'billing_year', 'billing_month'], name='milk_bill_sub_period_idx'),
        ),
        migrations.AddIndex(
            model_name='milkbill',
            index=models.Index(fields=['status', '-created_at'], name='milk_bill_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='milkbill',
            constraint=models.UniqueConstraint(fields=('subscription', 'billing_month', 'billing_year'), name='unique_milk_bill_month'),
        ),
    ]
