# Generated by Django 4.2.30 on 2026-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_app', '0013_milksubscription_milksubscriptionitem_milkdelivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='active', max_length=20),
        ),
    ]
