# Generated by Django 4.2.30 on 2026-09-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_app', '0014_alter_milksubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkbill',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkbill',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
