# Generated by Django 4.2.30 on 2026-09-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdf_app', '0017_alter_product_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, default='', editable=False, max_length=320),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, default='', editable=False, max_length=160),
        ),
    ]
